---
title: "Visualização dos casos de corona vírus no Brasil"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{figs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = FALSE, 
                      comment = FALSE, 
                      fig.width = 5, 
                      fig.height = 5)
```


```{r pkgs}
library(ggplot2)
library(dplyr)
library(rgdal)
library(sf)
library(tmap)
library(brazilmaps)
```


## Crescimento nacional no número de casos

```{r dados}
# carregando dados
dados <- read.csv("output/corona_brasil01.csv")
br <- get_brmap(geo = "State",
                class = "sf")
estados <- data.frame(uid = br$State, 
                      nome = br$nome)

# fazendo todas as modificacoes aqui
dados <- dados %>% 
  dplyr::rename(Casos = cases) %>%
  mutate(date = as.Date(date), 
         uid = as.factor(uid)) %>%
  filter(date > '2020-02-25') %>% # para pegar a partir do primeiro caso
  merge(., estados, by = "uid")
df <- dados %>% 
  select(-uid, -nome) %>%
  group_by(date, id_date) %>%
  summarise_all(sum)
```

```{r fig-casos, fig.width=6}
ggplot(df, aes(x = date, y = Casos, color = "red")) + 
  geom_line(alpha = .7) +
  geom_point(size = 2) +
  labs(x = "Data", 
       y = "Número de casos confirmados", 
       title = "Número de casos confirmados de corona vírus no Brasil") +
  scale_x_date(date_breaks = "1 day", 
               date_labels = "%d/%m") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        legend.position = "none")
```


## Entendendo o aumento diário

```{r fig-perc, fig.width=6}
df$delta_cases <- df$Casos - lag(df$Casos)
df$diff_perc <- round(df$delta_cases/df$Casos, 3) * 100
df$label <- paste(df$delta_cases, "%")
ggplot(df, aes(x = date, y = delta_cases)) + 
  geom_bar(stat = "identity", alpha = .7, color = "red", fill = "red") +
  #coord_flip() 
  scale_x_date(date_breaks = "1 day", 
               date_labels = "%d/%m") +
  scale_y_continuous(limits = c(0, max(df$delta_cases, na.rm = TRUE) + 3), 
                     expand = c(0, 0)) +
  geom_text(aes(label = label), 
            size = 2.5, 
            vjust = -0.5) + 
  labs(x = "Data", 
       y = "% de aumento", 
       title = "Porcentagem de aumento nos casos confirmados") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90))
```

## Número de casos por estado brasileiro

```{r mapa, message = FALSE}
df_uf <- dados %>% 
  group_by(uid, nome, date) %>%
  summarise_at(vars(Casos), sum) %>%
  ungroup() %>% 
  dplyr::rename(State = uid) %>%
  dplyr::mutate(log_cases = log(Casos + 1), 
                State = as.factor(State))

br_sf <- st_as_sf(br) %>%  
  merge(df_uf)
  
tm_shape(br_sf) +
  tm_fill() +
  tm_borders() +
  #tm_shape() +
  tm_symbols(size = "Casos", 
             col = "red", 
             border.col = "red",
             scale = 2, 
             alpha = 0.7)
#tm_facets(by = "date", free.coords = FALSE)
```

## Crescimento do número de casos nos estados mais afetados

```{r estados, fig.width=6}
uf10 <- df_uf %>% 
  filter(date == max(date), Casos > 9) %>%
  select(State)
df_uf %>% filter(State %in% uf10$State) %>% 
  ggplot(aes(x = date, y = Casos, col = nome)) + 
  geom_line() +
  geom_point() +
  labs(x = "Data", 
       y = "Número de casos confirmados", 
       title = "Estados com mais de 10 casos", 
       fill = "UF") +
  guides(color = guide_legend("UF")) +
  scale_color_brewer(palette = "Set2") +
  scale_x_date(date_breaks = "1 day", 
               date_labels = "%d/%m") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        legend.title = element_text(size = 7), 
        legend.text = element_text(size = 7))
```


## Evolução do número de casos por estado

```{r facet-map}
df_date <- dados %>% 
  group_by(uid, date) %>%
  summarise_at(vars(Casos), sum) %>%
  dplyr::rename(State = uid) #%>%
  #dplyr::mutate(cases = log(cases + 1))

date_sf <- st_as_sf(br) %>%  
  merge(df_date)

all_map <- tm_shape(br) +
  #tm_fill(col = "white") +
  tm_borders() +
  tm_polygons() +
  #br_sf %>%  merge(df_date) %>%
  tm_shape(date_sf) +
  tm_fill() +
  tm_borders() +
  tm_symbols(size = "Casos",
             border.col = "red", 
             col = "red", 
             scale = 1, 
             alpha = 0.7) +
  tm_facets(by = "date", free.coords = FALSE)
```


```{r anim, eval = T, fig.show = "animate"}
anim <- tm_shape(br) +
  tm_borders() +
  tm_polygons() +
  tm_shape(date_sf) +
  tm_symbols(size = "Casos",
             border.col = "red", 
             col = "red",
             scale = 2,
             alpha = 0.7) +
  tm_facets(along = "date", free.coords = FALSE)

anim
# tmap_animation(anim, filename = "figs/anim.gif", delay = 25, 
#                 width = 1200, height = 1200, res = 300)
```


