---
title: "Visualização dos casos registrados de COVID-19 no Brasil"
output: rmarkdown::html_vignette
date: "`r Sys.Date()`"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, 
                      warning = FALSE, results = TRUE, 
                      comment = FALSE, 
                      fig.width = 5, 
                      fig.height = 5)
devtools::load_all()
```


```{r pkgs, eval = FALSE}
library(coronabr)
```


## Crescimento nacional no número de casos

```{r get}
dados <- get_corona_br(by_uf = TRUE)
```


```{r fig-casos, fig.width=6}
plot_corona_br(df = dados, log = FALSE)
```


## Entendendo o aumento diário

```{r fig-perc, fig.width=6}
plot_corona_br(df = dados, tipo = "aumento")
```

## Casos por estado brasileiro

### Gráfico proporcional ao tamanho populacional (Casos por 100 mil habitantes)

```{r estados, fig.width=6}
plot_uf(df = dados, n = 7)
```

### Gráfico com o número bruto de notificações

```{r estados2, fig.width=6}
plot_uf(df = dados, prop_pop = FALSE, n = 7)
```

### Gráfico com o número bruto de óbitos

```{r obitos, fig.width=6}
plot_uf(df = dados, tipo = "obitos", prop_pop = FALSE, n = 7)
```


### Gráfico com o número de óbitos por 100 mil habitantes

```{r obitos_prop, fig.width=6}
plot_uf(df = dados, tipo = "obitos", prop_pop = TRUE, n = 7)
```

### Comparando estados específicos

```{r comp_estados, fig.width=6}
plot_uf(df = dados, 
        tipo = "casos",
        prop_pop = TRUE,
        estados = c("AM", "CE", "PE", "SP"))
```

